config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  devise_scope :user do
    authenticated :user do
      root to: 'recipes#index', as: :authenticated_root
    end

    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  root 'recipes#index'
  get '/public_recipes', to: 'public_recipes#index'

  resources :users, only: %i[index show]

  resources :recipes, only: %i[index show new create destroy] do
    member do
      patch :toggle_public
    end
    resources :recipe_foods, only: %i[create destroy index new]
  end

  resources :foods, only: %i[index show new create destroy]

  resources :shopping_lists, only: [:index]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /recipes or /recipes.json
  def index
    @recipes = current_user.recipes
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.includes(:recipe_foods, :user).find(params[:id])
    @user = @recipe.user
    @recipe_foods = @recipe.recipe_foods
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipes_path, notice: 'Recipe Created Successfully' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to recipes_url, notice: 'Recipe was successfully deleted.'
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)

    redirect_to recipe_path(@recipe)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<div class="new-recipe">
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.text_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.text_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/recipes/index.html.erb
<div class="recipe-container">
  <h1>Recipes</h1>

  <%= link_to 'New Recipe', new_recipe_path, class: 'new-recipe-button' %>
      <div class="recipe-list-inone">
      <% @recipes.each do |recipe| %>
        <div class="recipe-list">
          <div class="left">
            <%= link_to recipe.name, recipe %>
            <% if can?(:destroy, recipe) %>
              <%= button_to "Remove",
                            recipe,
                            method: :delete,
                            title: "Delete recipe",
                            class: "delete" %>
            <% end %>
          </div>
          Description: <%= recipe.description %>
        </div>
      <% end %>
      </div>

</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>
<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>
<div class="recipe-item">
  <div class="left">
    <p><strong>Preparation Time:</strong>
      <% if @recipe.preparation_time.present? %>
        <%= @recipe.preparation_time.strftime("%H:%M:%S") %>
      <% else %>
        Not specified
      <% end %>
    </p>
    <p><strong>Cooking Time:</strong>
      <% if @recipe.cooking_time.present? %>
        <%= @recipe.cooking_time.strftime("%H:%M:%S") %>
      <% else %>
        Not specified
      <% end %>
    </p>
    <p><strong>Created By:</strong><%= @recipe.user.name %></p>
    <%= link_to "Generate shopping list", shopping_lists_path , class: "add-food-button-in-recipe", disabled: true %>
  </div>
  <div>
    <div class="right">
      <p>Public </p>
      <% if can?(:toggle_public, @recipe) %>
        <%= form_with(model: @recipe, url: toggle_public_recipe_path(@recipe), method: :patch, html: { class: 'toggle-button' }) do |form| %>
          <%= form.check_box :on,
                          role: "switch",
                          checked: @recipe.public,
                          onchange: "this.form.submit()" %>
          <%= form.label :on, class: "toggle-button-label" %>
        <% end %>
      <% end %>
    </div>
    <%= link_to "Add ingredient", new_recipe_recipe_food_path(@recipe) , class: "add-food-button", disabled: true %>
  </div>
</div>
 
<h2>Foods:</h2>
<table class="food-table">
  <thead class="show-head">
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Value</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @recipe_foods.each_with_index do |recipe_food, index| %>
      <tr class="<%= index.even? ? 'light-row' : 'dark-row' %>">
        <td><%= recipe_food.food.name %></td>
        <td><%= recipe_food.quantity %><%= recipe_food.food.measurement_unit %></td>
        <td>$ <%= recipe_food.food.price * recipe_food.quantity %></td>
        <td class="show-td">
          <%= link_to 'Modify', class: 'modify-button' %>
          <%if can?(:destroy, recipe_food) %>
          <%= button_to 'Remove', food_path(recipe_food.food), method: :delete, data: { confirm: 'Are you sure you want to delete this food item?' }, class: 'remove-button' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>