config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  devise_scope :user do
    authenticated :user do
      root to: 'recipes#index', as: :authenticated_root
    end

    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  root 'recipes#index'
  get '/public_recipes', to: 'public_recipes#index'

  resources :users, only: %i[index show]

  resources :recipes, only: %i[index show new create destroy] do
    member do
      patch :toggle_public
    end
    resources :recipe_foods, only: %i[create destroy index new]
  end

  resources :foods, only: %i[index show new create destroy]

  resources :shopping_lists, only: [:index]
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true
  validates :measurement_unit, presence: true
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /foods or /foods.json
  def index
    @foods = current_user.foods
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = current_user.foods.build(food_params)

    if @food.save
      redirect_to foods_url, notice: 'Food was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food = current_user.foods.includes(:category).find(params[:id])
    @food.destroy
    redirect_to foods_url, notice: 'Food was successfully deleted.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Measurement_unit:</strong>
    <%= food.measurement_unit %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= food.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= food.quantity %>
  </p>

  <p>
    <strong>User:</strong>
    <%= food.user_id %>
  </p>

</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurement_unit, style: "display: block" %>
    <%= form.text_field :measurement_unit %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/index.html.erb
<div class='food-container'>
<h1>Foods</h1>
  <div class='button-box'>
    <%= link_to "Add Food", new_food_path, class: "add-food-button" %>
  </div>
  <table class="food-table">
    <thead>
      <tr>
        <th>Food Name</th>
        <th>Quantity</th>
        <th>Measurement Unit</th>
        <th>Unit Price</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each_with_index do |food, index| %>
        <tr class="<%= index.even? ? 'light-row' : 'dark-row' %>">
          <td><%= food.name %></td>
          <td><%= food.quantity %></td>
          <td><%= food.measurement_unit %></td>
          <td>$ <%= food.price %></td>
          <td>
            <% if current_user == food.user %>
              <%= button_to "Delete", food_path(food), method: :delete, data: { confirm: "Are you sure you want to delete this food?" }, class: 'delete-button'%>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<div class='container'>
  <div class='button-box'>
    <%= link_to "Add Food", new_food_path, class: "add-food-button" %>
  </div>
  <table class="food-table">
    <thead>
      <tr>
        <th>Food Name</th>
        <th>Quantity</th>
        <th>Measurement Unit</th>
        <th>Unit Price</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each_with_index do |food, index| %>
        <tr class="<%= index.even? ? 'light-row' : 'dark-row' %>">
          <td><%= food.name %></td>
          <td><%= food.quantity %></td>
          <td><%= food.measurement_unit %></td>
          <td>$ <%= food.price %></td>
          <td>
            <% if current_user == food.user %>
              <%= button_to "Delete", food_path(food), method: :delete, data: { confirm: "Are you sure you want to delete this food?" }, class: 'delete-button'%>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>