config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  devise_scope :user do
    authenticated :user do
      root to: 'recipes#index', as: :authenticated_root
    end

    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  root 'recipes#index'
  get '/public_recipes', to: 'public_recipes#index'

  resources :users, only: %i[index show]

  resources :recipes, only: %i[index show new create destroy] do
    member do
      patch :toggle_public
    end
    resources :recipe_foods, only: %i[create destroy index new]
  end

  resources :foods, only: %i[index show new create destroy]

  resources :shopping_lists, only: [:index]
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @foods = Food.all
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @new_recipe = @recipe.recipe_foods.new(recipe_food_params)
    @foods = Food.all

    if @new_recipe.save
      flash[:notice] = 'Ingredient was added successfully.'
      redirect_to recipe_path(@recipe.id)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    recipe_food = RecipeFood.find(params[:id])
    authorize! :destroy, recipe_food
    recipe = recipe_food.recipe
    recipe_food.destroy
    redirect_to recipe_path(recipe)
    flash[:notice] = 'Ingredient was deleted'
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/_form.html.erb
<%= form_with(model: recipe_food) do |form| %>
  <% if recipe_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>

      <ul>
        <% recipe_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :quntity, style: "display: block" %>
    <%= form.number_field :quntity %>
  </div>

  <div>
    <%= form.label :recipe_id, style: "display: block" %>
    <%= form.text_field :recipe_id %>
  </div>

  <div>
    <%= form.label :food_id, style: "display: block" %>
    <%= form.text_field :food_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipe_foods/_recipe_food.html.erb
<div id="<%= dom_id recipe_food %>">
  <p>
    <strong>Quntity:</strong>
    <%= recipe_food.quntity %>
  </p>

  <p>
    <strong>Recipe:</strong>
    <%= recipe_food.recipe_id %>
  </p>

  <p>
    <strong>Food:</strong>
    <%= recipe_food.food_id %>
  </p>

</div>

app/views/recipe_foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipe foods</h1>

<div id="recipe_foods">
  <% @recipe_foods.each do |recipe_food| %>
    <%= render recipe_food %>
    <p>
      <%= link_to "Show this recipe food", recipe_food %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe food", new_recipe_food_path %>

app/views/recipe_foods/new.html.erb
<div>
      <%=form_with url: recipe_recipe_foods_path, class:"form", scope: :recipe_food do |f| %>
        <div class="">
          <div class="">
            <%= f.select :food_id, @foods.collect { |food| [food.name, food.id] }, :prompt => 'Select an Ingredient', class: 'focus:outline-none', required: true %>
          </div>
          <div>
            <%= f.label :quantity, 'Quantity:' %>
            <%= f.number_field :quantity, step: :any, required: true, class: ''%>
          </div>
        </div>
        <div>
          <%= f.submit "Add Ingredient", class: ''%>
        </div> 
      <% end %>
    </div>
  </div>

app/views/recipe_foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe_food %>

<div>
  <%= link_to "Edit this recipe food", edit_recipe_food_path(@recipe_food) %> |
  <%= link_to "Back to recipe foods", recipe_foods_path %>

  <%= button_to "Destroy this recipe food", @recipe_food, method: :delete %>
</div>