config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  devise_scope :user do
    authenticated :user do
      root to: 'recipes#index', as: :authenticated_root
    end

    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  root 'recipes#index'
  get '/public_recipes', to: 'public_recipes#index'

  resources :users, only: %i[index show]

  resources :recipes, only: %i[index show new create destroy] do
    member do
      patch :toggle_public
    end
    resources :recipe_foods, only: %i[create destroy index new]
  end

  resources :foods, only: %i[index show new create destroy]

  resources :shopping_lists, only: [:index]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorRecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
  <% if user_signed_in? %> 
  <div class="nav-container">
  <nav>
    <ul>
      <%= image_tag("res.png", class: "logo") %>
      <li><%= link_to "Recipes", recipes_path %></li>
      <li><%= link_to "Foods", foods_path %></li>
      <li><%= link_to "Public Recipes", public_recipes_path %></li>
      <li><%= link_to "Shopping Lists", shopping_lists_path %></li>
    </ul>
  </nav>
  <%= link_to "sign_out", destroy_user_session_path, data:{turbo_method: :delete} %>
  </div>
  <% end %>
  
  
  
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
  
</html>